[workspace]
resolver = "2"
members = [
    "body_parser",
    "graphql",
    "schema_validator",
    "jwt_validator",
    "module",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[workspace.dependencies]
mlua = { version = "0.11", features = ["macros"] }
haproxy-api = { version = "0.9" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
hmac = "0.12"
base64 = "0.22"
