"""add certificate kind and server certificate fks

Revision ID: 81c898db0531
Revises: ed2234cbf245
Create Date: 2026-08-12 14:51:13.944384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c898db0531'
down_revision: Union[str, Sequence[str], None] = 'ed2234cbf245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(table_name: str, column_name: str) -> bool:
    from sqlalchemy import inspect
    conn = op.get_bind()
    return any(c["name"] == column_name for c in inspect(conn).get_columns(table_name))


def _table_exists(table_name: str) -> bool:
    from sqlalchemy import inspect
    conn = op.get_bind()
    return table_name in inspect(conn).get_table_names()


def upgrade() -> None:
    """Upgrade schema."""
    if not _table_exists("certificates"):
        return

    if not _column_exists("certificates", "kind"):
        with op.batch_alter_table('certificates', schema=None) as batch_op:
            batch_op.add_column(sa.Column('kind', sa.String(), nullable=True))
        op.execute("UPDATE certificates SET kind = 'server' WHERE kind IS NULL")
    else:
        op.execute("UPDATE certificates SET kind = 'server' WHERE kind IS NULL OR kind = ''")

    if _table_exists("servers"):
        with op.batch_alter_table('servers', schema=None) as batch_op:
            if not _column_exists("servers", "client_certificate_id"):
                batch_op.add_column(sa.Column('client_certificate_id', sa.Integer(), nullable=True))
            if not _column_exists("servers", "ca_certificate_id"):
                batch_op.add_column(sa.Column('ca_certificate_id', sa.Integer(), nullable=True))
            # Foreign key names are auto-generated; creating them repeatedly on
            # legacy databases may fail, so only add them if not present.
            conn = op.get_bind()
            fks = conn.dialect.get_foreign_keys(conn, "servers")
            existing_fk_cols = {
                tuple(fk.get("constrained_columns", []))
                for fk in fks
                if fk.get("referred_table") == "certificates"
            }
            if ("client_certificate_id",) not in existing_fk_cols:
                batch_op.create_foreign_key('fk_servers_client_certificate_id_certificates', 'certificates', ['client_certificate_id'], ['id'], ondelete='SET NULL')
            if ("ca_certificate_id",) not in existing_fk_cols:
                batch_op.create_foreign_key('fk_servers_ca_certificate_id_certificates', 'certificates', ['ca_certificate_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('client_certificate_id')
        batch_op.drop_column('ca_certificate_id')

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
