"""baseline

Revision ID: 8b9ba74c6828
Revises: 
Create Date: 2026-08-10 17:59:26.698426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9ba74c6828'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asn_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asn_lists_id'), 'asn_lists', ['id'], unique=False)
    op.create_index(op.f('ix_asn_lists_name'), 'asn_lists', ['name'], unique=True)
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_wildcard', sa.Boolean(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('cert_path', sa.String(), nullable=True),
    sa.Column('key_path', sa.String(), nullable=True),
    sa.Column('chain_path', sa.String(), nullable=True),
    sa.Column('not_before', sa.DateTime(), nullable=True),
    sa.Column('not_after', sa.DateTime(), nullable=True),
    sa.Column('subject_cn', sa.String(), nullable=True),
    sa.Column('sans', sa.String(), nullable=True),
    sa.Column('key_type', sa.String(), nullable=True),
    sa.Column('acme_challenge', sa.String(), nullable=True),
    sa.Column('acme_ca', sa.String(), nullable=True),
    sa.Column('dns_provider', sa.String(), nullable=True),
    sa.Column('dns_credentials', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_index(op.f('ix_certificates_name'), 'certificates', ['name'], unique=True)
    op.create_table('cipher_suites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('baseline', sa.String(), nullable=False),
    sa.Column('ciphers', sa.Text(), nullable=False),
    sa.Column('tls_options', sa.String(), nullable=True),
    sa.Column('min_tls_version', sa.String(), nullable=True),
    sa.Column('quantum_safe', sa.Boolean(), nullable=True),
    sa.Column('hsts_enabled', sa.Boolean(), nullable=True),
    sa.Column('hsts_max_age', sa.Integer(), nullable=True),
    sa.Column('hsts_include_subdomains', sa.Boolean(), nullable=True),
    sa.Column('hsts_preload', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cipher_suites_id'), 'cipher_suites', ['id'], unique=False)
    op.create_index(op.f('ix_cipher_suites_name'), 'cipher_suites', ['name'], unique=True)
    op.create_table('config_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('snapshot_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_snapshots_id'), 'config_snapshots', ['id'], unique=False)
    op.create_table('dynamic_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('list_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('update_interval_hours', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('target_list_id', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_entry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_feeds_id'), 'dynamic_feeds', ['id'], unique=False)
    op.create_index(op.f('ix_dynamic_feeds_name'), 'dynamic_feeds', ['name'], unique=True)
    op.create_table('fcgi_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('docroot', sa.String(), nullable=True),
    sa.Column('index_file', sa.String(), nullable=True),
    sa.Column('path_info', sa.String(), nullable=True),
    sa.Column('log_stderr_enabled', sa.Boolean(), nullable=True),
    sa.Column('log_stderr_target', sa.String(), nullable=True),
    sa.Column('keep_conn', sa.Boolean(), nullable=True),
    sa.Column('mpxs_conns', sa.Boolean(), nullable=True),
    sa.Column('max_reqs', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fcgi_apps_id'), 'fcgi_apps', ['id'], unique=False)
    op.create_index(op.f('ix_fcgi_apps_name'), 'fcgi_apps', ['name'], unique=True)
    op.create_table('geo_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_lists_id'), 'geo_lists', ['id'], unique=False)
    op.create_index(op.f('ix_geo_lists_name'), 'geo_lists', ['name'], unique=True)
    op.create_table('ja4_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ja4_lists_id'), 'ja4_lists', ['id'], unique=False)
    op.create_index(op.f('ix_ja4_lists_name'), 'ja4_lists', ['name'], unique=True)
    op.create_table('metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('process_info', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_snapshots_captured_at'), 'metric_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_id'), 'metric_snapshots', ['id'], unique=False)
    op.create_table('network_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_lists_id'), 'network_lists', ['id'], unique=False)
    op.create_index(op.f('ix_network_lists_name'), 'network_lists', ['name'], unique=True)
    op.create_table('page_protect_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('backend_ids', sa.JSON(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('sample_rate_percent', sa.Integer(), nullable=True),
    sa.Column('report_path', sa.String(), nullable=True),
    sa.Column('directives', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_protect_policies_id'), 'page_protect_policies', ['id'], unique=False)
    op.create_index(op.f('ix_page_protect_policies_name'), 'page_protect_policies', ['name'], unique=True)
    op.create_table('page_protect_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('first_hash', sa.String(), nullable=True),
    sa.Column('first_hash_at', sa.DateTime(), nullable=True),
    sa.Column('last_hash', sa.String(), nullable=True),
    sa.Column('hash_checked_at', sa.DateTime(), nullable=True),
    sa.Column('hash_changed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_protect_scripts_domain'), 'page_protect_scripts', ['domain'], unique=False)
    op.create_index(op.f('ix_page_protect_scripts_id'), 'page_protect_scripts', ['id'], unique=False)
    op.create_index(op.f('ix_page_protect_scripts_url'), 'page_protect_scripts', ['url'], unique=True)
    op.create_table('pattern_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_lists_id'), 'pattern_lists', ['id'], unique=False)
    op.create_index(op.f('ix_pattern_lists_name'), 'pattern_lists', ['name'], unique=True)
    op.create_table('security_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('listener_ids', sa.JSON(), nullable=True),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('expression_ast', sa.JSON(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('log', sa.Boolean(), nullable=True),
    sa.Column('no_log', sa.Boolean(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('redirect_url', sa.String(), nullable=True),
    sa.Column('redirect_code', sa.Integer(), nullable=True),
    sa.Column('error_page_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_rules_id'), 'security_rules', ['id'], unique=False)
    op.create_index(op.f('ix_security_rules_name'), 'security_rules', ['name'], unique=True)
    op.create_index(op.f('ix_security_rules_priority'), 'security_rules', ['priority'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('waf_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('msg', sa.String(), nullable=True),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waf_metrics_captured_at'), 'waf_metrics', ['captured_at'], unique=False)
    op.create_index(op.f('ix_waf_metrics_id'), 'waf_metrics', ['id'], unique=False)
    op.create_table('waf_siem_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('integration_type', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('auth_header', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waf_siem_integrations_id'), 'waf_siem_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_waf_siem_integrations_name'), 'waf_siem_integrations', ['name'], unique=True)
    op.create_table('asn_list_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['asn_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asn_list_entries_id'), 'asn_list_entries', ['id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['config_snapshots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_snapshot_id'), 'audit_events', ['snapshot_id'], unique=False)
    op.create_table('backends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('algorithm', sa.String(), nullable=True),
    sa.Column('sticky_sessions', sa.Boolean(), nullable=True),
    sa.Column('cookie_name', sa.String(), nullable=True),
    sa.Column('balance_args', sa.String(), nullable=True),
    sa.Column('health_check_enabled', sa.Boolean(), nullable=True),
    sa.Column('health_check_interval', sa.Integer(), nullable=True),
    sa.Column('health_check_uri', sa.String(), nullable=True),
    sa.Column('health_check_method', sa.String(), nullable=True),
    sa.Column('health_check_expect_status', sa.String(), nullable=True),
    sa.Column('health_check_expect_body', sa.String(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('redispatch', sa.Boolean(), nullable=True),
    sa.Column('timeout_queue', sa.Integer(), nullable=True),
    sa.Column('timeout_check', sa.Integer(), nullable=True),
    sa.Column('timeout_tunnel', sa.Integer(), nullable=True),
    sa.Column('http_reuse', sa.String(), nullable=True),
    sa.Column('fullconn', sa.Integer(), nullable=True),
    sa.Column('stick_table', sa.Boolean(), nullable=True),
    sa.Column('stick_table_size', sa.String(), nullable=True),
    sa.Column('stick_table_expire', sa.String(), nullable=True),
    sa.Column('stick_table_type', sa.String(), nullable=True),
    sa.Column('persist', sa.Boolean(), nullable=True),
    sa.Column('resolvers', sa.String(), nullable=True),
    sa.Column('host_header', sa.String(), nullable=True),
    sa.Column('fcgi_app_id', sa.Integer(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('haproxy_options', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fcgi_app_id'], ['fcgi_apps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backends_id'), 'backends', ['id'], unique=False)
    op.create_index(op.f('ix_backends_name'), 'backends', ['name'], unique=True)
    op.create_table('csp_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.Column('document_uri', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('violated_directive', sa.String(), nullable=True),
    sa.Column('effective_directive', sa.String(), nullable=True),
    sa.Column('original_policy', sa.Text(), nullable=True),
    sa.Column('blocked_uri', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('column_number', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('script_sample', sa.Text(), nullable=True),
    sa.Column('backend_name', sa.String(), nullable=True),
    sa.Column('listener_name', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['page_protect_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csp_reports_blocked_uri'), 'csp_reports', ['blocked_uri'], unique=False)
    op.create_index(op.f('ix_csp_reports_captured_at'), 'csp_reports', ['captured_at'], unique=False)
    op.create_index(op.f('ix_csp_reports_id'), 'csp_reports', ['id'], unique=False)
    op.create_index(op.f('ix_csp_reports_violated_directive'), 'csp_reports', ['violated_directive'], unique=False)
    op.create_table('geo_list_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['geo_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_list_entries_id'), 'geo_list_entries', ['id'], unique=False)
    op.create_table('ja4_list_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['ja4_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ja4_list_entries_id'), 'ja4_list_entries', ['id'], unique=False)
    op.create_table('network_list_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['network_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_list_entries_id'), 'network_list_entries', ['id'], unique=False)
    op.create_table('pattern_list_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['pattern_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_list_entries_id'), 'pattern_list_entries', ['id'], unique=False)
    op.create_table('cache_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backend_id', sa.Integer(), nullable=False),
    sa.Column('haproxy_enabled', sa.Boolean(), nullable=True),
    sa.Column('haproxy_total_max_size', sa.Integer(), nullable=True),
    sa.Column('haproxy_max_object_size', sa.Integer(), nullable=True),
    sa.Column('haproxy_max_age', sa.Integer(), nullable=True),
    sa.Column('haproxy_process_vary', sa.Boolean(), nullable=True),
    sa.Column('haproxy_max_secondary_entries', sa.Integer(), nullable=True),
    sa.Column('haproxy_cache_condition', sa.String(), nullable=True),
    sa.Column('disk_cache_enabled', sa.Boolean(), nullable=True),
    sa.Column('disk_cache_ttl', sa.Integer(), nullable=True),
    sa.Column('disk_cache_grace', sa.Integer(), nullable=True),
    sa.Column('disk_cache_purge_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['backend_id'], ['backends.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_configs_backend_id'), 'cache_configs', ['backend_id'], unique=True)
    op.create_index(op.f('ix_cache_configs_id'), 'cache_configs', ['id'], unique=False)
    op.create_table('cache_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_config_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cache_config_id'], ['cache_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_rules_cache_config_id'), 'cache_rules', ['cache_config_id'], unique=False)
    op.create_index(op.f('ix_cache_rules_id'), 'cache_rules', ['id'], unique=False)
    op.create_table('cache_metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('backend_id', sa.Integer(), nullable=True),
    sa.Column('haproxy_stats', sa.JSON(), nullable=True),
    sa.Column('disk_cache_stats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['backend_id'], ['backends.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_metric_snapshots_backend_id'), 'cache_metric_snapshots', ['backend_id'], unique=False)
    op.create_index(op.f('ix_cache_metric_snapshots_created_at'), 'cache_metric_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_cache_metric_snapshots_id'), 'cache_metric_snapshots', ['id'], unique=False)
    op.create_table('listeners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bind_address', sa.String(), nullable=True),
    sa.Column('bind_port', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('ssl_enabled', sa.Boolean(), nullable=True),
    sa.Column('certificate_id', sa.Integer(), nullable=True),
    sa.Column('certificate_ids', sa.JSON(), nullable=True),
    sa.Column('http2', sa.Boolean(), nullable=True),
    sa.Column('quic', sa.Boolean(), nullable=True),
    sa.Column('alpn', sa.String(), nullable=True),
    sa.Column('proxy_protocol', sa.Boolean(), nullable=True),
    sa.Column('force_https', sa.Boolean(), nullable=True),
    sa.Column('default_backend_id', sa.Integer(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('haproxy_options', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.ForeignKeyConstraint(['default_backend_id'], ['backends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listeners_id'), 'listeners', ['id'], unique=False)
    op.create_index(op.f('ix_listeners_name'), 'listeners', ['name'], unique=True)
    op.create_table('request_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backend_id', sa.Integer(), nullable=True),
    sa.Column('backend_ids', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['backend_id'], ['backends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_headers_id'), 'request_headers', ['id'], unique=False)
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backend_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('maxconn', sa.Integer(), nullable=True),
    sa.Column('check', sa.Boolean(), nullable=True),
    sa.Column('backup', sa.Boolean(), nullable=True),
    sa.Column('inter', sa.Integer(), nullable=True),
    sa.Column('rise', sa.Integer(), nullable=True),
    sa.Column('fall', sa.Integer(), nullable=True),
    sa.Column('slowstart', sa.Integer(), nullable=True),
    sa.Column('maxqueue', sa.Integer(), nullable=True),
    sa.Column('ssl', sa.Boolean(), nullable=True),
    sa.Column('verify', sa.String(), nullable=True),
    sa.Column('verifyhost', sa.String(), nullable=True),
    sa.Column('ca_file', sa.String(), nullable=True),
    sa.Column('client_cert', sa.String(), nullable=True),
    sa.Column('ciphers', sa.String(), nullable=True),
    sa.Column('alpn', sa.String(), nullable=True),
    sa.Column('sni', sa.String(), nullable=True),
    sa.Column('check_ssl', sa.Boolean(), nullable=True),
    sa.Column('check_sni', sa.String(), nullable=True),
    sa.Column('check_port', sa.Integer(), nullable=True),
    sa.Column('send_proxy', sa.Boolean(), nullable=True),
    sa.Column('send_proxy_v2', sa.Boolean(), nullable=True),
    sa.Column('resolve', sa.Boolean(), nullable=True),
    sa.Column('init_addr', sa.String(), nullable=True),
    sa.Column('agent_check', sa.Boolean(), nullable=True),
    sa.Column('agent_port', sa.Integer(), nullable=True),
    sa.Column('track', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['backend_id'], ['backends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_id'), 'servers', ['id'], unique=False)
    op.create_table('backend_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listener_id', sa.Integer(), nullable=False),
    sa.Column('backend_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('condition_type', sa.String(), nullable=True),
    sa.Column('condition_name', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['backend_id'], ['backends.id'], ),
    sa.ForeignKeyConstraint(['listener_id'], ['listeners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backend_rules_id'), 'backend_rules', ['id'], unique=False)
    op.create_table('custom_error_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listener_id', sa.Integer(), nullable=True),
    sa.Column('listener_ids', sa.JSON(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['listener_id'], ['listeners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_error_pages_id'), 'custom_error_pages', ['id'], unique=False)
    op.create_table('log_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listener_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('facility', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['listener_id'], ['listeners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_destinations_id'), 'log_destinations', ['id'], unique=False)
    op.create_index(op.f('ix_log_destinations_name'), 'log_destinations', ['name'], unique=True)
    op.create_table('logged_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listener_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['listener_id'], ['listeners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logged_fields_id'), 'logged_fields', ['id'], unique=False)
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listener_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('limit_type', sa.String(), nullable=True),
    sa.Column('events', sa.Integer(), nullable=True),
    sa.Column('window_seconds', sa.Integer(), nullable=True),
    sa.Column('burst', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('match_status_code', sa.Integer(), nullable=True),
    sa.Column('url_path', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('waf_event_threshold', sa.Integer(), nullable=True),
    sa.Column('waf_window_seconds', sa.Integer(), nullable=True),
    sa.Column('waf_block_duration', sa.Integer(), nullable=True),
    sa.Column('log', sa.Boolean(), nullable=True),
    sa.Column('no_log', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['listener_id'], ['listeners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limits_id'), 'rate_limits', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limits_name'), 'rate_limits', ['name'], unique=True)
    op.create_table('response_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listener_id', sa.Integer(), nullable=True),
    sa.Column('listener_ids', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['listener_id'], ['listeners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_headers_id'), 'response_headers', ['id'], unique=False)
    op.create_table('rewrites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listener_id', sa.Integer(), nullable=True),
    sa.Column('listener_ids', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('host_match', sa.String(), nullable=True),
    sa.Column('source_regex', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['listener_id'], ['listeners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewrites_id'), 'rewrites', ['id'], unique=False)
    op.create_index(op.f('ix_rewrites_name'), 'rewrites', ['name'], unique=True)
    op.create_index(op.f('ix_rewrites_priority'), 'rewrites', ['priority'], unique=False)
    op.create_table('waf_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listener_id', sa.Integer(), nullable=True),
    sa.Column('backend_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('rule_set', sa.String(), nullable=True),
    sa.Column('rule_set_version', sa.String(), nullable=True),
    sa.Column('rule_set_url', sa.String(), nullable=True),
    sa.Column('rule_set_sha256', sa.String(), nullable=True),
    sa.Column('rule_set_auto_update', sa.Boolean(), nullable=True),
    sa.Column('rule_set_update_interval_hours', sa.Integer(), nullable=True),
    sa.Column('rule_set_last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('rule_set_last_error', sa.String(), nullable=True),
    sa.Column('rule_set_plugins', sa.JSON(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('paranoia_level', sa.Integer(), nullable=True),
    sa.Column('inbound_anomaly_threshold', sa.Integer(), nullable=True),
    sa.Column('outbound_anomaly_threshold', sa.Integer(), nullable=True),
    sa.Column('sec_rules', sa.Text(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('redirect_url', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('captcha_valid_seconds', sa.Integer(), nullable=True),
    sa.Column('path_pattern', sa.String(), nullable=True),
    sa.Column('http_methods', sa.String(), nullable=True),
    sa.Column('content_types', sa.String(), nullable=True),
    sa.Column('export_rule_ids', sa.Boolean(), nullable=True),
    sa.Column('rate_enabled', sa.Boolean(), nullable=True),
    sa.Column('rate_events', sa.Integer(), nullable=True),
    sa.Column('rate_window_seconds', sa.Integer(), nullable=True),
    sa.Column('rate_key', sa.String(), nullable=True),
    sa.Column('rate_header', sa.String(), nullable=True),
    sa.Column('rate_action', sa.String(), nullable=True),
    sa.Column('rate_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('fail_open', sa.Boolean(), nullable=True),
    sa.Column('siem_integration_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['backend_id'], ['backends.id'], ),
    sa.ForeignKeyConstraint(['listener_id'], ['listeners.id'], ),
    sa.ForeignKeyConstraint(['siem_integration_id'], ['waf_siem_integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waf_rules_id'), 'waf_rules', ['id'], unique=False)
    op.create_index(op.f('ix_waf_rules_name'), 'waf_rules', ['name'], unique=True)
    op.create_table('redirects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listener_id', sa.Integer(), nullable=True),
    sa.Column('listener_ids', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('preserve_query', sa.Boolean(), nullable=True),
    sa.Column('error_page_id', sa.Integer(), nullable=True),
    sa.Column('error_page_query', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['error_page_id'], ['custom_error_pages.id'], ),
    sa.ForeignKeyConstraint(['listener_id'], ['listeners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redirects_id'), 'redirects', ['id'], unique=False)
    op.create_index(op.f('ix_redirects_name'), 'redirects', ['name'], unique=True)
    op.create_index(op.f('ix_redirects_priority'), 'redirects', ['priority'], unique=False)
    op.create_table('waf_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waf_rule_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('rule_tag', sa.String(), nullable=True),
    sa.Column('rule_msg', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('variable', sa.String(), nullable=True),
    sa.Column('matcher', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('update_action', sa.String(), nullable=True),
    sa.Column('update_target', sa.String(), nullable=True),
    sa.Column('condition_variable', sa.String(), nullable=True),
    sa.Column('condition_operator', sa.String(), nullable=True),
    sa.Column('condition_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['waf_rule_id'], ['waf_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waf_exceptions_id'), 'waf_exceptions', ['id'], unique=False)
    op.create_table('waf_rule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waf_rule_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['waf_rule_id'], ['waf_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waf_rule_versions_id'), 'waf_rule_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waf_rule_versions_id'), table_name='waf_rule_versions')
    op.drop_table('waf_rule_versions')
    op.drop_index(op.f('ix_waf_exceptions_id'), table_name='waf_exceptions')
    op.drop_table('waf_exceptions')
    op.drop_index(op.f('ix_redirects_priority'), table_name='redirects')
    op.drop_index(op.f('ix_redirects_name'), table_name='redirects')
    op.drop_index(op.f('ix_redirects_id'), table_name='redirects')
    op.drop_table('redirects')
    op.drop_index(op.f('ix_waf_rules_name'), table_name='waf_rules')
    op.drop_index(op.f('ix_waf_rules_id'), table_name='waf_rules')
    op.drop_table('waf_rules')
    op.drop_index(op.f('ix_rewrites_priority'), table_name='rewrites')
    op.drop_index(op.f('ix_rewrites_name'), table_name='rewrites')
    op.drop_index(op.f('ix_rewrites_id'), table_name='rewrites')
    op.drop_table('rewrites')
    op.drop_index(op.f('ix_response_headers_id'), table_name='response_headers')
    op.drop_table('response_headers')
    op.drop_index(op.f('ix_rate_limits_name'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_id'), table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_index(op.f('ix_logged_fields_id'), table_name='logged_fields')
    op.drop_table('logged_fields')
    op.drop_index(op.f('ix_log_destinations_name'), table_name='log_destinations')
    op.drop_index(op.f('ix_log_destinations_id'), table_name='log_destinations')
    op.drop_table('log_destinations')
    op.drop_index(op.f('ix_custom_error_pages_id'), table_name='custom_error_pages')
    op.drop_table('custom_error_pages')
    op.drop_index(op.f('ix_backend_rules_id'), table_name='backend_rules')
    op.drop_table('backend_rules')
    op.drop_index(op.f('ix_servers_id'), table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_request_headers_id'), table_name='request_headers')
    op.drop_table('request_headers')
    op.drop_index(op.f('ix_listeners_name'), table_name='listeners')
    op.drop_index(op.f('ix_listeners_id'), table_name='listeners')
    op.drop_table('listeners')
    op.drop_index(op.f('ix_cache_metric_snapshots_id'), table_name='cache_metric_snapshots')
    op.drop_index(op.f('ix_cache_metric_snapshots_created_at'), table_name='cache_metric_snapshots')
    op.drop_index(op.f('ix_cache_metric_snapshots_backend_id'), table_name='cache_metric_snapshots')
    op.drop_table('cache_metric_snapshots')
    op.drop_index(op.f('ix_cache_rules_id'), table_name='cache_rules')
    op.drop_index(op.f('ix_cache_rules_cache_config_id'), table_name='cache_rules')
    op.drop_table('cache_rules')
    op.drop_index(op.f('ix_cache_configs_id'), table_name='cache_configs')
    op.drop_index(op.f('ix_cache_configs_backend_id'), table_name='cache_configs')
    op.drop_table('cache_configs')
    op.drop_index(op.f('ix_pattern_list_entries_id'), table_name='pattern_list_entries')
    op.drop_table('pattern_list_entries')
    op.drop_index(op.f('ix_network_list_entries_id'), table_name='network_list_entries')
    op.drop_table('network_list_entries')
    op.drop_index(op.f('ix_ja4_list_entries_id'), table_name='ja4_list_entries')
    op.drop_table('ja4_list_entries')
    op.drop_index(op.f('ix_geo_list_entries_id'), table_name='geo_list_entries')
    op.drop_table('geo_list_entries')
    op.drop_index(op.f('ix_csp_reports_violated_directive'), table_name='csp_reports')
    op.drop_index(op.f('ix_csp_reports_id'), table_name='csp_reports')
    op.drop_index(op.f('ix_csp_reports_captured_at'), table_name='csp_reports')
    op.drop_index(op.f('ix_csp_reports_blocked_uri'), table_name='csp_reports')
    op.drop_table('csp_reports')
    op.drop_index(op.f('ix_backends_name'), table_name='backends')
    op.drop_index(op.f('ix_backends_id'), table_name='backends')
    op.drop_table('backends')
    op.drop_index(op.f('ix_audit_events_snapshot_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_asn_list_entries_id'), table_name='asn_list_entries')
    op.drop_table('asn_list_entries')
    op.drop_index(op.f('ix_waf_siem_integrations_name'), table_name='waf_siem_integrations')
    op.drop_index(op.f('ix_waf_siem_integrations_id'), table_name='waf_siem_integrations')
    op.drop_table('waf_siem_integrations')
    op.drop_index(op.f('ix_waf_metrics_id'), table_name='waf_metrics')
    op.drop_index(op.f('ix_waf_metrics_captured_at'), table_name='waf_metrics')
    op.drop_table('waf_metrics')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_security_rules_priority'), table_name='security_rules')
    op.drop_index(op.f('ix_security_rules_name'), table_name='security_rules')
    op.drop_index(op.f('ix_security_rules_id'), table_name='security_rules')
    op.drop_table('security_rules')
    op.drop_index(op.f('ix_pattern_lists_name'), table_name='pattern_lists')
    op.drop_index(op.f('ix_pattern_lists_id'), table_name='pattern_lists')
    op.drop_table('pattern_lists')
    op.drop_index(op.f('ix_page_protect_scripts_url'), table_name='page_protect_scripts')
    op.drop_index(op.f('ix_page_protect_scripts_id'), table_name='page_protect_scripts')
    op.drop_index(op.f('ix_page_protect_scripts_domain'), table_name='page_protect_scripts')
    op.drop_table('page_protect_scripts')
    op.drop_index(op.f('ix_page_protect_policies_name'), table_name='page_protect_policies')
    op.drop_index(op.f('ix_page_protect_policies_id'), table_name='page_protect_policies')
    op.drop_table('page_protect_policies')
    op.drop_index(op.f('ix_network_lists_name'), table_name='network_lists')
    op.drop_index(op.f('ix_network_lists_id'), table_name='network_lists')
    op.drop_table('network_lists')
    op.drop_index(op.f('ix_metric_snapshots_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_captured_at'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index(op.f('ix_ja4_lists_name'), table_name='ja4_lists')
    op.drop_index(op.f('ix_ja4_lists_id'), table_name='ja4_lists')
    op.drop_table('ja4_lists')
    op.drop_index(op.f('ix_geo_lists_name'), table_name='geo_lists')
    op.drop_index(op.f('ix_geo_lists_id'), table_name='geo_lists')
    op.drop_table('geo_lists')
    op.drop_index(op.f('ix_fcgi_apps_name'), table_name='fcgi_apps')
    op.drop_index(op.f('ix_fcgi_apps_id'), table_name='fcgi_apps')
    op.drop_table('fcgi_apps')
    op.drop_index(op.f('ix_dynamic_feeds_name'), table_name='dynamic_feeds')
    op.drop_index(op.f('ix_dynamic_feeds_id'), table_name='dynamic_feeds')
    op.drop_table('dynamic_feeds')
    op.drop_index(op.f('ix_config_snapshots_id'), table_name='config_snapshots')
    op.drop_table('config_snapshots')
    op.drop_index(op.f('ix_cipher_suites_name'), table_name='cipher_suites')
    op.drop_index(op.f('ix_cipher_suites_id'), table_name='cipher_suites')
    op.drop_table('cipher_suites')
    op.drop_index(op.f('ix_certificates_name'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_asn_lists_name'), table_name='asn_lists')
    op.drop_index(op.f('ix_asn_lists_id'), table_name='asn_lists')
    op.drop_table('asn_lists')
    # ### end Alembic commands ###
