"""add auto_apply to dynamic feeds

Revision ID: a69151848ae7
Revises: dcb10692d124
Create Date: 2026-09-09 11:42:17.563811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69151848ae7'
down_revision: Union[str, Sequence[str], None] = 'dcb10692d124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_apply', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_feeds', schema=None) as batch_op:
        batch_op.drop_column('auto_apply')

    # ### end Alembic commands ###
