"""WAF rule, exception, CRS, and snapshot endpoints."""
import json
import os
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple
from fastapi import APIRouter, Depends, File, Form, HTTPException, Query, Request, Response, UploadFile, status
from fastapi.responses import FileResponse, HTMLResponse, RedirectResponse
from sqlalchemy.orm import Session
from starlette.background import BackgroundTask
from ..deps import get_current_user, get_db, oauth2_scheme, require_admin, require_write, rate_limit, rate_limit_by_ip
from ...core.config import get_settings
from ...models.models import *
from ...schemas.settings import SettingCreate, SettingResponse
from ...schemas.waf import *
from ...services.coraza_config import *
from ...services.haproxy import reload_haproxy, write_config
from ...services.settings import get_setting, set_setting
from ...services.tasks import get_task, queue_task
from ...services.waf_metrics import get_waf_metrics

settings = get_settings()
router = APIRouter()


# WAF
@router.get("/waf-rules", response_model=List[WafRuleResponse])
def list_waf_rules(db: Session = Depends(get_db), user=Depends(get_current_user), _=Depends(rate_limit)):
    return db.query(WafRule).all()


@router.post("/waf-rules", response_model=WafRuleResponse)
def create_waf_rule(r: WafRuleCreate, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    obj = WafRule(**r.model_dump())
    db.add(obj)
    db.commit()
    db.refresh(obj)
    return obj


@router.put("/waf-rules/{rid}", response_model=WafRuleResponse)
def update_waf_rule(rid: int, r_in: WafRuleUpdate, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    obj = db.get(WafRule, rid)
    if not obj:
        raise HTTPException(status_code=404, detail="WAF rule not found")
    for k, v in r_in.model_dump(exclude_unset=True).items():
        setattr(obj, k, v)
    db.commit()
    db.refresh(obj)
    return obj


@router.delete("/waf-rules/{rid}")
def delete_waf_rule(rid: int, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    obj = db.get(WafRule, rid)
    if not obj:
        raise HTTPException(status_code=404, detail="WAF rule not found")
    db.delete(obj)
    db.commit()
    return {"status": "ok"}


@router.get("/waf-exceptions", response_model=List[WafExceptionResponse])
def list_waf_exceptions(db: Session = Depends(get_db), user=Depends(get_current_user), _=Depends(rate_limit)):
    return db.query(WafException).all()


@router.post("/waf-exceptions", response_model=WafExceptionResponse)
def create_waf_exception(e: WafExceptionCreate, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    obj = WafException(**e.model_dump())
    db.add(obj)
    db.commit()
    db.refresh(obj)
    return obj


@router.put("/waf-exceptions/{eid}", response_model=WafExceptionResponse)
def update_waf_exception(eid: int, e_in: WafExceptionUpdate, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    obj = db.get(WafException, eid)
    if not obj:
        raise HTTPException(status_code=404, detail="Exception not found")
    for k, v in e_in.model_dump(exclude_unset=True).items():
        setattr(obj, k, v)
    db.commit()
    db.refresh(obj)
    return obj


@router.delete("/waf-exceptions/{eid}")
def delete_waf_exception(eid: int, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    obj = db.get(WafException, eid)
    if not obj:
        raise HTTPException(status_code=404, detail="Exception not found")
    db.delete(obj)
    db.commit()
    return {"status": "ok"}


@router.get("/waf/captcha", response_class=HTMLResponse)
def get_captcha_challenge(
    request: Request,
    cid: str = Query(""),
    db: Session = Depends(get_db),
    _=Depends(rate_limit_by_ip),
):
    from ...services.captcha_providers import get_provider, render_challenge_page, render_error_page

    cfg = get_settings()
    provider_name = get_setting(db, "captcha_provider", "cap") or "cap"
    # Determine the site key for the active provider
    site_key = _get_provider_site_key(db, provider_name, cfg)
    if not site_key:
        return HTMLResponse(
            render_error_page("CAPTCHA Not Configured", "Set the site key and secret for the active captcha provider.", "", 503),
            status_code=503,
        )
    # Look up the challenge context from Valkey using the opaque token.
    # The token was generated by HAProxy's captcha_ctx Lua action and stored
    # server-side with a 120-second TTL. This keeps internal rule details
    # (rule_id, rule_type, rule_name, request_id) and the redirect destination
    # out of the URL entirely, preventing open redirect attacks.
    rule_id = 0
    rule_type = "waf"
    rule_name = ""
    request_id = ""
    redirect_url = "/"
    if cid:
        from ...core.valkey_client import cache_get, cache_set
        context = cache_get(f"cap:cid:{cid}")
        if context and isinstance(context, dict):
            rule_id = int(context.get("i", 0))
            rule_type = str(context.get("t", "waf"))
            rule_name = str(context.get("n", ""))
            request_id = str(context.get("r", ""))
            redirect_url = str(context.get("u", "/"))
        # Delete the token after reading (single-use)
        from ...core import valkey_client
        client = valkey_client._get_client()
        if client:
            try:
                client.delete(f"cap:cid:{cid}")
            except Exception:
                pass

    cap_path = cfg.CAPTCHA_PROXY_PATH.rstrip("/")
    target = redirect_url
    # Build provider instance (reCAPTCHA needs version + min_score from settings)
    provider = _build_provider(db, provider_name, cfg)
    # Render provider-specific widget + script + CSP
    widget_html = provider.render_widget_html(site_key, cap_path)
    script_html = provider.render_script_html(cfg)
    csp = provider.get_csp_directives()
    hidden_fields = {
        "redirect": target,
        "rule_id": str(rule_id),
        "rule_type": rule_type,
        "rule_name": rule_name,
        "request_id": request_id,
    }
    html = render_challenge_page(
        widget_html=widget_html,
        script_html=script_html,
        csp=csp,
        form_action=f"{cap_path}/verify",
        hidden_fields=hidden_fields,
        request_id=request_id,
        is_invisible=provider.is_invisible(),
    )
    # Log challenge issued event with request_id
    _log_challenge_event(db, rule_id, rule_type, rule_name, "issued", request_id=request_id or None)
    return HTMLResponse(html)


@router.post("/waf/verify-captcha")
async def verify_captcha(
    request: Request,
    redirect: str = Form("/"),
    cap_token: Optional[str] = Form(None),
    g_recaptcha_response: Optional[str] = Form(None, alias="g-recaptcha-response"),
    cf_turnstile_response: Optional[str] = Form(None, alias="cf-turnstile-response"),
    rule_id: int = Form(0),
    rule_type: str = Form("waf"),
    rule_name: str = Form(""),
    request_id: str = Form(""),
    db: Session = Depends(get_db),
    _=Depends(rate_limit_by_ip),
):
    from ...services.captcha_providers import get_provider, render_error_page

    cfg = get_settings()
    provider_name = get_setting(db, "captcha_provider", "cap") or "cap"
    provider = _build_provider(db, provider_name, cfg)
    token_field = provider.get_token_field_name()
    # Pick the token from the provider-specific form field
    if token_field == "cap_token":
        token = cap_token
    elif token_field == "g-recaptcha-response":
        token = g_recaptcha_response
    elif token_field == "cf-turnstile-response":
        token = cf_turnstile_response
    else:
        token = None
    secret = _get_provider_secret(db, provider_name, cfg)
    if not secret:
        _log_challenge_event(db, rule_id, rule_type, rule_name, "failed", request_id=request_id or None)
        return HTMLResponse(
            render_error_page("Verification Failed", "Captcha secret is not configured. Set the secret key for the active captcha provider.", request_id, 400),
            status_code=400,
        )
    if not token:
        _log_challenge_event(db, rule_id, rule_type, rule_name, "failed", request_id=request_id or None)
        return HTMLResponse(
            render_error_page("Verification Failed", "No captcha token received. Please try again.", request_id, 400),
            status_code=400,
        )
    try:
        success = await provider.verify(token, secret, remote_ip=None)
    except Exception as exc:
        _log_challenge_event(db, rule_id, rule_type, rule_name, "failed", request_id=request_id or None)
        return HTMLResponse(
            render_error_page("Service Unavailable", f"Captcha verification service is temporarily unavailable.", request_id, 502),
            status_code=502,
        )

    if not success:
        _log_challenge_event(db, rule_id, rule_type, rule_name, "failed", request_id=request_id or None)
        return HTMLResponse(
            render_error_page("Verification Failed", "Captcha verification failed. Please try again.", request_id, 403),
            status_code=403,
        )

    _log_challenge_event(db, rule_id, rule_type, rule_name, "solved", request_id=request_id or None)
    # Ignore the client-supplied TTL — it comes from a hidden form field that
    # was populated from the query string, both of which are user-controlled.
    # An attacker could change the TTL to a huge value to get a long-lived
    # bypass cookie after solving just one challenge. Always use the
    # server-side captcha_valid_seconds setting instead.
    server_ttl = int(get_setting(db, "captcha_valid_seconds", "3600") or 3600)
    max_age = max(0, server_ttl)
    # Generate an opaque random token and store it in Valkey with the same TTL
    # as the cookie. HAProxy validates the cookie by looking up the token in
    # Valkey via a Lua action — if the key exists, the user previously solved
    # a challenge and the TTL hasn't expired. This replaces the old cap_valid=1
    # cookie which was trivially forgeable (any value bypassed challenge rules
    # because HAProxy only checked for cookie existence).
    #
    # The token is bound to the client that solved the challenge via a hash of
    # the client IP + User-Agent + JA4 TLS fingerprint. The HAProxy Lua action
    # recomputes this hash from the live request and compares it to the stored
    # value, so a leaked cookie cannot be replayed from a different client.
    import secrets as _secrets
    from ...core.valkey_client import set_cv_token
    from ...services.captcha_providers import compute_cv_binding_hash
    cookie_token = _secrets.token_hex(32)
    client_ip = request.client.host if request.client else ""
    user_agent = request.headers.get("user-agent", "")
    ja4_fp = request.headers.get("x-ja4-fingerprint", "")
    binding_hash = compute_cv_binding_hash(client_ip, user_agent, ja4_fp)
    # Valkey TTL must be > 0; if max_age is 0 (session cookie), use 1 hour
    cv_ttl = max_age if max_age > 0 else 3600
    set_cv_token(cookie_token, binding_hash, ttl=cv_ttl)
    response = RedirectResponse(url=redirect, status_code=302)
    response.set_cookie(
        key="_cv",
        value=cookie_token,
        max_age=max_age,
        httponly=True,
        samesite="lax",
    )
    return response


def _get_provider_site_key(db: Session, provider_name: str, cfg: Any) -> Optional[str]:
    """Return the site key for the active provider (settings table > env var)."""
    if provider_name == "cap":
        return get_setting(db, "cap_site_key") or cfg.CAPTCHA_SITE_KEY
    elif provider_name == "recaptcha":
        return get_setting(db, "recaptcha_site_key") or cfg.RECAPTCHA_SITE_KEY
    elif provider_name == "turnstile":
        return get_setting(db, "turnstile_site_key") or cfg.TURNSTILE_SITE_KEY
    return None


def _get_provider_secret(db: Session, provider_name: str, cfg: Any) -> Optional[str]:
    """Return the secret for the active provider (settings table > env var)."""
    if provider_name == "cap":
        return get_setting(db, "cap_secret") or cfg.CAPTCHA_SECRET
    elif provider_name == "recaptcha":
        return get_setting(db, "recaptcha_secret") or cfg.RECAPTCHA_SECRET
    elif provider_name == "turnstile":
        return get_setting(db, "turnstile_secret") or cfg.TURNSTILE_SECRET
    return None


def _build_provider(db: Session, provider_name: str, cfg: Any):
    """Build a provider instance, reading version/min_score for reCAPTCHA."""
    from ...services.captcha_providers import get_provider
    if provider_name == "recaptcha":
        version = get_setting(db, "recaptcha_version") or cfg.RECAPTCHA_VERSION or "v2"
        min_score = float(get_setting(db, "recaptcha_min_score") or cfg.RECAPTCHA_MIN_SCORE or 0.5)
        return get_provider("recaptcha", version=version, min_score=min_score)
    return get_provider(provider_name)


def _log_challenge_event(db: Session, rule_id: int, rule_type: str, rule_name: str, event_type: str, request_id: Optional[str] = None) -> None:
    """Log a ChallengeEvent for per-rule solve rate statistics."""
    try:
        from ...models.waf import ChallengeEvent
        db.add(ChallengeEvent(
            rule_type=rule_type,
            rule_id=rule_id if rule_id > 0 else None,
            rule_name=rule_name or None,
            event_type=event_type,
            client_ip=None,
            request_id=request_id,
        ))
        db.commit()
    except Exception:
        db.rollback()


@router.get("/waf/logs")
def get_waf_logs(limit: int = Query(100, le=1000), user=Depends(get_current_user), _=Depends(rate_limit)):
    from ...core.config import get_settings
    from ...services.waf_metrics import _parse_line
    path = get_settings().CORAZA_SPOA_LOG_PATH
    if not os.path.exists(path):
        return {"events": []}
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            lines = f.readlines()
        events = []
        for line in lines[-limit:]:
            line = line.strip()
            if not line:
                continue
            parsed = _parse_line(line)
            if parsed:
                parsed["raw"] = line
                events.append(parsed)
        return {"events": events[::-1]}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/waf/health")
def get_waf_health(user=Depends(get_current_user), _=Depends(rate_limit)):
    from ...core.config import get_settings
    from ...services.coraza_config import write_coraza_spoa_config
    from ...core.database import SessionLocal
    import socket
    import time
    from collections import deque

    cfg = get_settings()
    config_ok = os.path.exists(cfg.CORAZA_SPOA_CONFIG_PATH)
    log_ok = os.path.exists(cfg.CORAZA_SPOA_LOG_PATH)
    reachable = False
    latency_ms = None
    last_error = None
    try:
        start = time.time()
        with socket.create_connection((cfg.CORAZA_SPOA_HOST, cfg.CORAZA_SPOA_PORT), timeout=2):
            reachable = True
            latency_ms = round((time.time() - start) * 1000, 2)
    except Exception as e:
        last_error = str(e)

    generated = False
    db = None
    counts = {}
    last_log_line = None
    try:
        db = SessionLocal()
        write_coraza_spoa_config(db, restart=False)
        generated = True
        counts = {
            "waf_rules": db.query(WafRule).filter(WafRule.enabled == True).count(),
            "waf_exceptions": db.query(WafException).count(),
            "siem_integrations": db.query(WafSiemIntegration).filter(WafSiemIntegration.enabled == True).count(),
            "waf_rules_fail_open": db.query(WafRule).filter(WafRule.fail_open == True).count(),
        }
    except Exception as e:
        last_error = str(e)
    finally:
        if db:
            db.close()

    if log_ok:
        try:
            with open(cfg.CORAZA_SPOA_LOG_PATH, "r") as f:
                last_lines = deque(f, maxlen=1)
                if last_lines:
                    last_log_line = last_lines[0].strip()
        except Exception:
            pass

    return {
        "status": "ok" if (reachable and config_ok and generated) else "degraded",
        "coraza_spoa_reachable": reachable,
        "coraza_spoa_latency_ms": latency_ms,
        "config_present": config_ok,
        "log_present": log_ok,
        "config_generated": generated,
        "last_error": last_error,
        "last_log_line": last_log_line,
        "counts": counts,
        "spoa_targets": cfg.CORAZA_SPOA_TARGETS or f"{cfg.CORAZA_SPOA_HOST}:{cfg.CORAZA_SPOA_PORT}",
    }


# ---- CRS management ----

@router.get("/waf/crs/status")
def get_crs_status_endpoint(db: Session = Depends(get_db), user=Depends(get_current_user), _=Depends(rate_limit)):
    from ...services.crs_downloader import get_crs_status
    return get_crs_status(db)


@router.post("/waf/crs/download")
def download_crs_endpoint(db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    from ...services.crs_downloader import download_crs
    result = download_crs(db, created_by=user.username if user else None)
    if not result["ok"]:
        raise HTTPException(status_code=400, detail=result.get("error", "Download failed"))
    return result


@router.get("/waf/crs/snapshots")
def list_crs_snapshots_endpoint(db: Session = Depends(get_db), user=Depends(get_current_user), _=Depends(rate_limit)):
    from ...services.crs_downloader import list_crs_snapshots
    return list_crs_snapshots(db)


@router.post("/waf/crs/rollback/{snapshot_id}")
def rollback_crs_endpoint(snapshot_id: int, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    from ...services.crs_downloader import rollback_crs
    result = rollback_crs(db, snapshot_id, created_by=user.username if user else None)
    if not result["ok"]:
        raise HTTPException(status_code=400, detail=result.get("error", "Rollback failed"))
    return result


@router.delete("/waf/crs/snapshots/{snapshot_id}")
def delete_crs_snapshot_endpoint(snapshot_id: int, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    from ...services.crs_downloader import delete_crs_snapshot
    result = delete_crs_snapshot(db, snapshot_id)
    if not result["ok"]:
        raise HTTPException(status_code=400, detail=result.get("error", "Delete failed"))
    return result


@router.put("/waf/crs/pinned-version", response_model=SettingResponse)
def set_crs_pinned_version_endpoint(s_in: SettingCreate, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    from ...services.settings import set_setting
    version = s_in.value.strip() or None
    return set_setting(db, "crs_pinned_version", version)


@router.get("/waf/rules/export")
def export_waf_rules(db: Session = Depends(get_db), user=Depends(require_admin), _=Depends(rate_limit)):
    rules = [r.__dict__ for r in db.query(WafRule).all()]
    exceptions = [e.__dict__ for e in db.query(WafException).all()]
    for r in rules:
        r.pop("_sa_instance_state", None)
    for e in exceptions:
        e.pop("_sa_instance_state", None)
    return {"rules": rules, "exceptions": exceptions}


@router.post("/waf/rules/import")
def import_waf_rules(data: dict, db: Session = Depends(get_db), user=Depends(require_admin), _=Depends(rate_limit)):
    for r in data.get("rules", []):
        r.pop("id", None)
        r.pop("created_at", None)
        r.pop("updated_at", None)
        r.pop("_sa_instance_state", None)
        obj = WafRule(**r)
        db.merge(obj)
    db.commit()
    for e in data.get("exceptions", []):
        e.pop("id", None)
        e.pop("_sa_instance_state", None)
        obj = WafException(**e)
        db.merge(obj)
    db.commit()
    return {"status": "ok"}


@router.get("/waf/siem-integrations", response_model=List[WafSiemIntegrationResponse])
def list_waf_siem(db: Session = Depends(get_db), user=Depends(get_current_user), _=Depends(rate_limit)):
    return db.query(WafSiemIntegration).all()


@router.post("/waf/siem-integrations", response_model=WafSiemIntegrationResponse)
def create_waf_siem(s: WafSiemIntegrationCreate, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    obj = WafSiemIntegration(**s.model_dump())
    db.add(obj)
    db.commit()
    db.refresh(obj)
    return obj


@router.put("/waf/siem-integrations/{sid}", response_model=WafSiemIntegrationResponse)
def update_waf_siem(sid: int, s_in: WafSiemIntegrationUpdate, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    obj = db.get(WafSiemIntegration, sid)
    if not obj:
        raise HTTPException(status_code=404, detail="SIEM integration not found")
    for k, v in s_in.model_dump(exclude_unset=True).items():
        setattr(obj, k, v)
    db.commit()
    db.refresh(obj)
    return obj


@router.delete("/waf/siem-integrations/{sid}")
def delete_waf_siem(sid: int, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    obj = db.get(WafSiemIntegration, sid)
    if not obj:
        raise HTTPException(status_code=404, detail="SIEM integration not found")
    db.delete(obj)
    db.commit()
    return {"status": "ok"}


@router.get("/waf/rule-versions", response_model=List[WafRuleVersionResponse])
def list_waf_rule_versions(waf_rule_id: Optional[int] = None, db: Session = Depends(get_db), user=Depends(get_current_user), _=Depends(rate_limit)):
    q = db.query(WafRuleVersion)
    if waf_rule_id:
        q = q.filter(WafRuleVersion.waf_rule_id == waf_rule_id)
    return q.order_by(WafRuleVersion.created_at.desc()).all()


def _json_safe_rule(rule: WafRule) -> dict:
    """Convert a WafRule instance into a JSON-safe snapshot dict."""
    safe = {}
    for k, v in rule.__dict__.items():
        if k.startswith("_"):
            continue
        if hasattr(v, "isoformat"):
            safe[k] = v.isoformat()
        elif v is None or isinstance(v, (str, int, float, bool, list, dict)):
            safe[k] = v
        else:
            safe[k] = str(v)
    return safe


def _waf_rule_version_max(db: Session) -> int:
    """Return the per-rule max snapshot count (0 = unlimited).

    Prefers the DB-backed setting, falling back to the env var default.
    """
    default = str(settings.WAF_RULE_VERSION_MAX_PER_RULE)
    try:
        return int(get_setting(db, "waf_rule_version_max_per_rule", default) or default)
    except (TypeError, ValueError):
        return settings.WAF_RULE_VERSION_MAX_PER_RULE


def _prune_waf_rule_versions(db: Session, waf_rule_id: int) -> int:
    """Delete oldest snapshots beyond the per-rule max for the given rule.

    Returns the number of snapshots removed. No-op when max is 0 (unlimited).
    """
    max_keep = _waf_rule_version_max(db)
    if max_keep <= 0:
        return 0
    total = db.query(WafRuleVersion).filter(WafRuleVersion.waf_rule_id == waf_rule_id).count()
    if total <= max_keep:
        return 0
    to_remove = (
        db.query(WafRuleVersion)
        .filter(WafRuleVersion.waf_rule_id == waf_rule_id)
        .order_by(WafRuleVersion.created_at.desc())
        .offset(max_keep)
        .all()
    )
    for v in to_remove:
        db.delete(v)
    db.commit()
    return len(to_remove)


@router.post("/waf/rules/{rid}/refresh-rule-set")
def refresh_rule_set(rid: int, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    """Manually trigger a download of a remote rule set."""
    rule = db.get(WafRule, rid)
    if not rule:
        raise HTTPException(status_code=404, detail="WAF rule not found")
    if rule.rule_set != "remote":
        raise HTTPException(status_code=400, detail="Rule set is not 'remote'")
    if not rule.rule_set_url:
        raise HTTPException(status_code=400, detail="No rule set URL configured")
    from ...services.rule_set_downloader import download_rule_set
    ok = download_rule_set(db, rule)
    if ok:
        from ...services import coraza_config
        coraza_config.write_coraza_spoa_config(db)
    return {"ok": ok, "error": rule.rule_set_last_error}


@router.post("/waf/rules/{rid}/snapshot", response_model=WafRuleVersionResponse)
def snapshot_waf_rule(rid: int, version: str, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    rule = db.get(WafRule, rid)
    if not rule:
        raise HTTPException(status_code=404, detail="WAF rule not found")
    snapshot = WafRuleVersion(
        waf_rule_id=rid,
        version=version,
        snapshot=_json_safe_rule(rule),
        created_by=user.username if user else None,
    )
    db.add(snapshot)
    db.commit()
    db.refresh(snapshot)
    _prune_waf_rule_versions(db, rid)
    return snapshot


@router.post("/waf/rules/{rid}/restore/{vid}", response_model=WafRuleResponse)
def restore_waf_rule(rid: int, vid: int, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    rule = db.get(WafRule, rid)
    if not rule:
        raise HTTPException(status_code=404, detail="WAF rule not found")
    snapshot = db.query(WafRuleVersion).filter(WafRuleVersion.id == vid, WafRuleVersion.waf_rule_id == rid).first()
    if not snapshot:
        raise HTTPException(status_code=404, detail="Snapshot not found")
    data = snapshot.snapshot
    data.pop("id", None)
    data.pop("created_at", None)
    data.pop("updated_at", None)
    data.pop("_sa_instance_state", None)
    for k, v in data.items():
        setattr(rule, k, v)
    db.commit()
    db.refresh(rule)
    return rule


@router.get("/waf/rule-versions/max", response_model=SettingResponse)
def get_waf_rule_version_max(db: Session = Depends(get_db), user=Depends(get_current_user), _=Depends(rate_limit)):
    default = str(settings.WAF_RULE_VERSION_MAX_PER_RULE)
    value = get_setting(db, "waf_rule_version_max_per_rule", default)
    row = db.query(Setting).filter(Setting.key == "waf_rule_version_max_per_rule").first()
    if not row:
        row = Setting(key="waf_rule_version_max_per_rule", value=value)
    return row


@router.put("/waf/rule-versions/max", response_model=SettingResponse)
def set_waf_rule_version_max(s_in: SettingCreate, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    try:
        val = int(s_in.value)
        if val < 0:
            raise ValueError
    except (TypeError, ValueError):
        raise HTTPException(status_code=400, detail="waf_rule_version_max_per_rule must be a non-negative integer (0 = unlimited)")
    return set_setting(db, "waf_rule_version_max_per_rule", str(val))


@router.delete("/waf/rule-versions/{vid}")
def delete_waf_rule_version(vid: int, db: Session = Depends(get_db), user=Depends(require_write), _=Depends(rate_limit)):
    snap = db.query(WafRuleVersion).filter(WafRuleVersion.id == vid).first()
    if not snap:
        raise HTTPException(status_code=404, detail="Snapshot not found")
    db.delete(snap)
    db.commit()
    return {"status": "ok"}


