apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-corex
  namespace: {{ include "corex-manager.namespace" . }}
  labels:
    {{- include "corex-manager.labels" . | nindent 4 }}
  {{- with .Values.corexService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.corexService.type }}
  {{- if and (eq .Values.corexService.type "NodePort") .Values.corexService.nodePort }}
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: {{ .Values.corexService.nodePort }}
      protocol: TCP
    - name: https
      port: 443
      targetPort: https
      nodePort: {{ add (int .Values.corexService.nodePort) 1 }}
      protocol: TCP
  {{- else }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
  {{- end }}
  selector:
    {{- include "corex-manager.podSelectorLabels" . | nindent 4 }}
