-- risk_score.lua — Risk Scoring engine for HAProxy
--
-- Provides two http-req actions:
--   lua.risk_capture  — derives 10 metadata fields from txn.req_fp.* vars,
--                       raw headers, GeoIP, and JA4. Stores in txn.risk_fp.*
--   lua.risk_compute  — reads per-rule match flags (txn.risk.match_<id>) +
--                       a generated points table (risk_rules_data.lua),
--                       sums points per ruleset, clamps each to [0,99],
--                       sets txn.risk.<slug>.score, txn.risk.<slug>.rules_hit,
--                       txn.risk.<slug>.rules_hit_count, and
--                       txn.risk.<slug>.hit_density for each ruleset.
--                       Also sets backward-compat aliases txn.risk.score,
--                       txn.risk.rules_hit, txn.risk.rules_hit_count,
--                       txn.risk.hit_density (= default ruleset values).
--
-- Loaded via: lua-load-per-thread /etc/haproxy/risk_score.lua
--
-- Both actions run in the http-req phase, so request data is read directly
-- from HAProxy sample fetches (txn.f) rather than from copies stashed in txn
-- vars; the script keeps no per-request state and is safe per-thread.
--
-- The risk_rules_data.lua file is generated by the Python backend at config
-- write time and contains:
--   return {
--     rulesets = { "default", "human", "api", "mobile" },
--     rules = {
--       { id = 1, ruleset = "default", points = 15, name = "...", log = true },
--       ...
--     }
--   }
-- It is loaded once per Lua state (see load_rules_data). Every config apply
-- reloads HAProxy, which re-creates the Lua states and re-reads the file, so
-- the cached table always matches the per-rule set-var flags emitted in the
-- running config.

-- In HAProxy's Lua runtime, `core` is a global provided by HAProxy itself
-- (not a Lua module on the package path), so we do NOT require() it.
-- The other Lua scripts (req_fp.lua, captcha_ctx.lua) rely on the same global.

local RULES_DATA_PATH = '/app/data/risk_rules_data.lua'
local EMPTY = {}

-- Cached rules table; nil until the first successful load so a transient
-- read failure (file not yet written) is retried on the next request.
local rules_data = nil

local function load_rules_data()
    if rules_data then return rules_data end
    local ok, loaded = pcall(dofile, RULES_DATA_PATH)
    if ok and type(loaded) == 'table' then
        rules_data = loaded
        return rules_data
    end
    return EMPTY
end

-- Approximate UTC offsets for the GeoIP timezones seen most often. Built once
-- at load time rather than per request.
local TZ_OFFSETS = {
    ['Asia/Tokyo'] = 9, ['Asia/Shanghai'] = 8, ['Asia/Kolkata'] = 5,
    ['Asia/Dubai'] = 4, ['Europe/London'] = 0, ['Europe/Paris'] = 1,
    ['Europe/Moscow'] = 3, ['America/New_York'] = -5, ['America/Chicago'] = -6,
    ['America/Denver'] = -7, ['America/Los_Angeles'] = -8, ['Australia/Sydney'] = 10,
    ['Pacific/Auckland'] = 12, ['UTC'] = 0,
    ['America/Sao_Paulo'] = -3, ['America/Mexico_City'] = -6,
    ['Africa/Lagos'] = 1, ['Africa/Johannesburg'] = 2,
    ['Asia/Singapore'] = 8, ['Asia/Seoul'] = 9, ['Asia/Hong_Kong'] = 8,
    ['Europe/Berlin'] = 1, ['Europe/Madrid'] = 1, ['Europe/Amsterdam'] = 1,
    ['Europe/Istanbul'] = 3, ['America/Toronto'] = -5, ['America/Vancouver'] = -8,
}

-- ---------------------------------------------------------------------------
-- Phase 1: risk_capture — derive metadata fields
-- ---------------------------------------------------------------------------

local function risk_capture(txn)
    -- Request-phase data straight from the fetches (no txn var copies).
    local ver = txn.f:req_ver() or '1.1'
    local path = txn.f:path() or '/'
    local query = txn.f:query() or ''
    local conn = (txn.f:req_hdr('connection') or ''):lower()
    local ua = txn.f:req_hdr('user-agent') or ''
    local alang = (txn.f:req_hdr('accept-language') or ''):lower()
    -- param_keys is set by the Rust haproxy-req-fp module.
    local param_keys = txn:get_var('txn.req_fp.param_keys') or ''

    -- 1. keep_alive (boolean as "0"/"1" string)
    local kl = '0'
    if ver:match('2') then kl = '1'
    elseif conn == 'close' then kl = '0'
    elseif conn == 'keep-alive' then kl = '1'
    elseif ver:match('1%.1') then kl = '1' end
    txn:set_var('txn.risk_fp.keep_alive', kl)

    -- 2. user_agent_length
    txn:set_var('txn.risk_fp.ua_len', tostring(#ua))

    -- 3. request_hour (local time 0-23, assumed UTC in Docker)
    local hour = tonumber(os.date('%H')) or 0
    txn:set_var('txn.risk_fp.req_hour', string.format('%02d', hour))

    -- 4. geo_lang_mismatch (boolean as "0"/"1" string)
    -- True when the GeoIP country code (lowercased) does NOT appear in the
    -- Accept-Language header. Also true if we have a country but no
    -- Accept-Language at all.
    local country = (txn:get_var('txn.geo_country') or ''):lower()
    local mismatch = '0'
    if country ~= '' and alang == '' then
        mismatch = '1'
    elseif country ~= '' and alang ~= '' and not alang:find(country, 1, true) then
        mismatch = '1'
    end
    txn:set_var('txn.risk_fp.geo_lang_mismatch', mismatch)

    -- 5-6. JA4 cipher_count + ext_count
    -- JA4 format: {proto}{version}{sni}{cipher_count}{ext_count}{alpn}_{hash}_{hash}
    -- e.g. t13d1516h2 → cipher_count=15, ext_count=16
    -- Positions 5-6 and 7-8 of the first segment (1-indexed: chars 5-6 and 7-8)
    local ja4 = ''
    local ok, fp = pcall(function() return txn.sf:ja4_fp() end)
    if ok and fp then ja4 = fp end
    local cc, ec = ja4:match('^%a%d%d%d(%d%d)(%d%d)')
    txn:set_var('txn.risk_fp.cipher_count', cc and tostring(tonumber(cc)) or '')
    txn:set_var('txn.risk_fp.ext_count', ec and tostring(tonumber(ec)) or '')

    -- 7. uri_length (path + query + "?" separator when query is non-empty)
    local uri_len = #path
    if query ~= '' then uri_len = uri_len + #query + 1 end
    txn:set_var('txn.risk_fp.uri_length', tostring(uri_len))

    -- 8. param_count
    -- param_keys is a string where each param contributes one first-char
    -- initial. "nil" sentinel means 0 params.
    local pcount = 0
    if param_keys ~= '' and param_keys ~= 'nil' then
        pcount = #param_keys
    end
    txn:set_var('txn.risk_fp.param_count', tostring(pcount))

    -- 9. version_numeric
    -- HTTP/0.9→9, HTTP/1.0→10, HTTP/1.1→11, HTTP/2.0→20, HTTP/3.0→30
    local vnum = 11
    if ver:match('0%.9') then vnum = 9
    elseif ver:match('1%.0') then vnum = 10
    elseif ver:match('1%.1') then vnum = 11
    elseif ver:match('2') then vnum = 20
    elseif ver:match('3') then vnum = 30 end
    txn:set_var('txn.risk_fp.version_numeric', tostring(vnum))

    -- 10. timezone_mismatch (boolean as "0"/"1" string)
    -- Compares the GeoIP timezone's UTC offset against the request hour.
    -- If the client's local hour (request_hour + tz_offset) would be outside
    -- 6am-11pm, flags as mismatch. Catches VPN/proxy use.
    local tz = txn:get_var('txn.geoip_tz') or ''
    local offset = TZ_OFFSETS[tz]
    if not offset then
        -- Unknown timezone — default to no mismatch (safe)
        txn:set_var('txn.risk_fp.tz_mismatch', '0')
    else
        local client_hour = (hour + offset) % 24
        local tz_mm = '0'
        if client_hour < 6 or client_hour > 23 then tz_mm = '1' end
        txn:set_var('txn.risk_fp.tz_mismatch', tz_mm)
    end
end

-- ---------------------------------------------------------------------------
-- Phase 3: risk_compute — sum points per ruleset from match flags + rules table
-- ---------------------------------------------------------------------------

local function risk_compute(txn)
    local data = load_rules_data()
    local ruleset_slugs = data.rulesets or EMPTY
    local rules = data.rules or EMPTY

    -- Initialize all ruleset scores to 0, hits to empty, counts to 0
    local scores = {}
    local hits = {}
    local counts = {}
    local total_enabled = {}  -- total enabled rules per ruleset (for hit_density)
    for _, slug in ipairs(ruleset_slugs) do
        scores[slug] = 0
        hits[slug] = {}
        counts[slug] = 0
        total_enabled[slug] = 0
    end

    -- Count total enabled rules per ruleset (for hit_density calculation)
    for _, rule in ipairs(rules) do
        local slug = rule.ruleset or 'default'
        if rule.enabled ~= false then
            total_enabled[slug] = (total_enabled[slug] or 0) + 1
        end
    end

    -- Sum points per ruleset
    for _, rule in ipairs(rules) do
        local match_var = 'txn.risk.match_' .. tostring(rule.id)
        local matched = txn:get_var(match_var)
        -- HAProxy bool(1) sets a typed boolean; txn:get_var returns a string.
        -- Truthiness: non-empty, non-"0", non-"false".
        if matched and matched ~= '' and matched ~= '0' and matched ~= 'false' then
            local slug = rule.ruleset or 'default'
            if not scores[slug] then scores[slug] = 0 end
            if not hits[slug] then hits[slug] = {} end
            if not counts[slug] then counts[slug] = 0 end
            scores[slug] = scores[slug] + (rule.points or 0)
            counts[slug] = counts[slug] + 1
            if rule.log and rule.name then
                hits[slug][#hits[slug] + 1] = rule.name
            end
        end
    end

    -- Set per-ruleset vars (score clamped 0-99, count is raw int)
    for slug, score in pairs(scores) do
        -- Compute hit_density: round(count / total_enabled * 100)
        local density = 0
        local total = total_enabled[slug] or 0
        if total > 0 then
            density = math.floor((counts[slug] or 0) / total * 100 + 0.5)
        end

        -- Clamp to [0, 99]
        if score < 0 then score = 0 end
        if score > 99 then score = 99 end
        scores[slug] = score  -- write back clamped value for default alias

        txn:set_var('txn.risk.' .. slug .. '.score', tostring(score))
        txn:set_var('txn.risk.' .. slug .. '.rules_hit', table.concat(hits[slug] or {}, ','))
        txn:set_var('txn.risk.' .. slug .. '.rules_hit_count', tostring(counts[slug] or 0))
        txn:set_var('txn.risk.' .. slug .. '.hit_density', tostring(density))
    end

    -- Set default aliases (risk.score = risk.default.score, etc.)
    local default_score = scores['default'] or 0
    if default_score < 0 then default_score = 0 end
    if default_score > 99 then default_score = 99 end
    txn:set_var('txn.risk.score', tostring(default_score))
    txn:set_var('txn.risk.rules_hit', table.concat(hits['default'] or {}, ','))
    txn:set_var('txn.risk.rules_hit_count', tostring(counts['default'] or 0))
    -- hit_density alias for default ruleset
    local default_density = 0
    local default_total = total_enabled['default'] or 0
    if default_total > 0 then
        default_density = math.floor((counts['default'] or 0) / default_total * 100 + 0.5)
    end
    txn:set_var('txn.risk.hit_density', tostring(default_density))
end

-- ---------------------------------------------------------------------------
-- Register actions
-- ---------------------------------------------------------------------------

core.register_action('risk_capture', { 'http-req' }, risk_capture)
core.register_action('risk_compute', { 'http-req' }, risk_compute)
