[package]
name = "haproxy-compression"
version = "0.1.0"
edition = "2021"
autotests = false
readme = "README.md"
keywords = ["haproxy", "brotli", "zstd", "compression"]
license = "MIT"
description = "HAProxy filter for brotli and zstd compression support"

[workspace]
members = [
    "module",
]

[dependencies]
mlua = { version = "0.11", features = ["macros"] }
haproxy-api = { version = "0.9" }
brotlic = "0.8"
zstd = "0.13"
